# Generated by Django 5.1.6 on 2026-01-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('limit', models.IntegerField(default=35)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subito_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price_str', models.CharField(blank=True, max_length=50, null=True)),
                ('price_num', models.FloatField(blank=True, null=True)),
                ('date_pub', models.CharField(blank=True, max_length=100, null=True)),
                ('date_pub_iso', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_type', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_cost', models.FloatField(blank=True, null=True)),
                ('shippable', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scraper.searchquery')),
            ],
            options={
                'ordering': ['-date_pub_iso'],
            },
        ),
    ]
