# Generated by Django 5.1.6 on 2026-01-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_searchquery_title_only_searchquery_total_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
