# Generated by Django 5.1.6 on 2026-01-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_geocache'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='likes_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='shippable_only',
            field=models.BooleanField(default=False),
        ),
    ]
