# Generated by Django 5.1.6 on 2026-01-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_favorite_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
