# Generated by Django 5.1.6 on 2026-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_savedsearch_province_savedsearch_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsearch',
            name='province',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='region',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='province',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='region',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='platform',
            field=models.CharField(choices=[('subito', 'Subito'), ('vinted', 'Vinted')], default='subito', max_length=20),
        ),
    ]
