# Generated by Django 5.1.6 on 2026-01-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_remove_savedsearch_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='platform',
            field=models.CharField(default='subito', max_length=20),
        ),
    ]
