# Generated by Django 5.2.11 on 2026-08-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_alter_searchquery_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='platform',
        ),
    ]
