# Generated by Django 5.2.11 on 2026-09-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_remove_searchquery_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='category',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
