# Generated by Django 5.2.11 on 2026-09-13 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_searchquery_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('query', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=10)),
                ('title_only', models.BooleanField(default=False)),
                ('shippable_only', models.BooleanField(default=False)),
                ('interval_seconds', models.IntegerField(default=30)),
                ('page_size', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_seeded', models.BooleanField(default=False)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('checks_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subito_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price_str', models.CharField(blank=True, max_length=50, null=True)),
                ('price_num', models.FloatField(blank=True, null=True)),
                ('date_pub', models.CharField(blank=True, max_length=100, null=True)),
                ('date_pub_iso', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_type', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_cost', models.FloatField(blank=True, null=True)),
                ('shippable', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True, default='')),
                ('defect_flag', models.CharField(blank=True, default='', max_length=50)),
                ('defect_reason', models.CharField(blank=True, default='', max_length=255)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_seed', models.BooleanField(default=False)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='scraper.monitor')),
            ],
            options={
                'ordering': ['-first_seen_at'],
                'constraints': [models.UniqueConstraint(fields=('monitor', 'subito_id'), name='uniq_monitor_subito_id')],
            },
        ),
    ]
