# Generated by Django 5.2.11 on 2026-09-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_monitor_monitorhit'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='seeded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
