# Generated by Django 5.2.11 on 2026-09-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_monitor_seeded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorhit',
            name='exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
