# Generated by Django 5.2.11 on 2026-09-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_monitorhit_exported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorhit',
            name='is_backfill',
            field=models.BooleanField(default=False),
        ),
    ]
